In [6]:
#Create a null vector of size 10 but the fifth value which is 1.
import numpy as np

arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#Create a vector with values ranging from 10 to 49
arr=np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [13]:
# Create a 3x3 matrix with values ranging from 0 to 8
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
numbers=[0,0,3,4,0,0]
print(f"Numbers: {numbers}")
zeroindices=np.nonzero(numbers)
print(zeroindices)

Numbers: [0, 0, 3, 4, 0, 0]
(array([2, 3], dtype=int64),)


In [27]:
#Create a 10x10 array with random values and find the minimum and maximum values.
arr=np.random.randint(100,size=(10,10))
print(arr)
print(np.min(arr))
print(np.max(arr))


[[22 97 59 71 87  3 39 99 95  8]
 [84 40 91 92 83 37 46 26 71 41]
 [44 72 97 18 27 47 51  9 62 54]
 [97 93 20 48 50 30 20 20  2 38]
 [32 47 68 31 85 16 16 72 78 11]
 [70 14 19 35 12 61 21 80 94 90]
 [ 8 63 29  5 69 64 60 96 40 80]
 [ 5 46  4 54 49 86  9 67 86  6]
 [76  7 97 75 36 78 83 87 16 49]
 [12 44 27 68 51 59 72  2 24 53]]
2
99


In [37]:
# Create a random vector of size 30 and find the mean value.

arr=np.random.random(30)
print(arr)

print(np.mean(arr))

[0.32945682 0.59891945 0.30538263 0.0256992  0.08865863 0.80265617
 0.04564705 0.53779551 0.49270708 0.98605721 0.14636969 0.2418544
 0.42779298 0.27065693 0.15371495 0.06764028 0.07072935 0.44266182
 0.02906374 0.44604759 0.36704925 0.75200542 0.30428132 0.75023294
 0.70845043 0.64179768 0.00911217 0.97439702 0.81207106 0.28605766]
0.40383221458898266
